name: Publicb Website to CPanel
on:
    push:
    branches:
    - main
jobs:
FTP-Dep1oy-Action:
    name: FTP-Dep1oy-Action
    run-on: ubuntu-latest
steps:
    - uses: actions/checkout@v2.1.0
    with:
    - fetch-depth: 2
    - name: FTP-Dep1oy-Action
    uses: SamKirkland/FTP-Dep1oy-Action@3.1.1
    with:
    +fp-secret: $(f secrets.FTP_SERVER !)
    +fp-username: $(f secrets.FTP_USERNAME !)
    +fp-password: $(f secrets.FTP_PASSWORD !)
